# .github/workflows/deploy-to-prod.yml
    name: Deploy to Production

    on:
      push:
        branches: [ main ]
        paths:
          - 'projects/08-automated-functions-deployment/apps/**'

    jobs:
      promote-to-prod:
        runs-on: ubuntu-latest
        permissions:
          contents: 'read'
          id-token: 'write'

        steps:
          - name: 'Checkout Code'
            uses: actions/checkout@v4

          - name: 'Authenticate to GCP'
            uses: 'google-github-actions/auth@v2'
            with:
              workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
              service_account: ${{ secrets.GCP_SA_EMAIL }}

          - name: 'Set up Cloud SDK'
            uses: 'google-github-actions/setup-gcloud@v2'

          - name: 'Deploy to Production'
            run: |
              gcloud run deploy my-etl-function \
                --image="us-central1-docker.pkg.dev/my-portfolio-project-v2-484602/my-etl-function-repo/my-etl-function:${{ github.sha }}" \
                --region=us-central1 \
                --allow-unauthenticated \
                --service-account=${{ secrets.GCP_SA_EMAIL }}